### ISSUE TITLE
Please make this compatible with laravel 5.8

### ISSUE THREAD

**Issue by Keagang** [codiiv/chatteradmin#1]
This project doesn't work when I am using the latest version of Laravel

**Comment by devuniverse** [comment]
After some investigation, it's the mother package ( https://github.com/thedevdojo/chatter/  ) that is not compatible with 5.8

**Comment by phprule** [comment]
> After some investigation, it's the mother package ( https://github.com/thedevdojo/chatter/ ) that is not compatible with 5.8

https://github.com/thedevdojo/chatter/pull/245
